name: Lining and type checking
run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - src/**
  push:
    branches-ignore:
      - main
      - dev
    paths:
      - src/**

jobs:
  linting_black:
    name: Linting with Black (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.12" ]
    uses: "./.github/workflows/black.yml"
    with:
      source_path: ./src
      python-version: ${{ matrix.python-version }}
      optional_feature: '--line-length 88 --verbose --diff --color'

  linting_flake8:
    name: Linting with flake8 (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.12" ]
    uses: "./.github/workflows/flake8.yml"
    with:
      source_path: ./src
      python-version: ${{ matrix.python-version }}

  typing_mypy:
    name: Checking static types with mypy (Python${{ matrix.python-version }})
    strategy:
      matrix:
        python-version: [ "3.12" ]
    uses: "./.github/workflows/mypy.yml"
    with:
      source_path: ./src
      python-version: ${{ matrix.python-version }}